### ISSUE TITLE
override is missing for methodQueue using ReactModule

### ISSUE THREAD

**Issue by svipas** [ikhvorost/ReactBridge#4] opened 2024-02-01 20:08 UTC
With `@ReactModule(methodQueue: DispatchQueue.main)` I get this error:

<img width="1392" alt="image" src="https://github.com/ikhvorost/ReactBridge/assets/10441177/53519fbd-3053-4ecb-b66c-a9bc46f809b3">

Seems like `override` is missing for `methodQueue`

**Comment by ikhvorost** [comment] 2024-02-02 09:16
Hi! Looks like your class inherits the other one  where `methodQueue` is already implemented. What class do you inherit your own or React's one? Please provide more info.

**Comment by ikhvorost** [comment] 2024-02-02 16:20
If you make a module class that inherits from `NSObject` you have nothing to override but if it inherits from a class that is already implemented `RCTBridgeModule`  (like `RCTBridgeModule` etc.) you have to and this is a question. I'm considering how to determine this case.

**Comment by ikhvorost** [comment] 2024-02-04 15:22
The issue is fixed in [1.0.4](https://github.com/ikhvorost/ReactBridge/releases/tag/1.0.4), please try it out and thanks for bug reporting!

**Comment by svipas** [comment] 2024-02-06 18:38
Thanks, I will try and I will let you know

**Closed** 2024-03-04 13:14 UTC
