### ISSUE TITLE
Getting Error while building XcFramework

### ISSUE THREAD

**Issue by Chaman-Sahu-iOS** [ikhvorost/ReactBridge#3] opened 2024-01-11 10:24 UTC
Thank you so much for making a great package. It helps me avoid Objective-C code while implementing the React Native Modules. Please help me solve this error, I am getting this error while building the XcFramework in iOS.

error: The package product 'SwiftSyntaxMacros' requires minimum platform version 13.0 for the iOS platform, but this target supports 12.0 (in target 'ReactBridgeMacros' from project 'ReactBridge')
error: The package product 'SwiftCompilerPlugin' requires minimum platform version 13.0 for the iOS platform, but this target supports 12.0 (in target 'ReactBridgeMacros' from project 'ReactBridge')

<img width="1316" alt="Screenshot 2024-01-11 at 3 53 44 PM" src="https://github.com/ikhvorost/ReactBridge/assets/118852284/078f26e2-dd52-40b4-97d1-3c997c6de9dd">

**Comment by ikhvorost** [comment] 2024-01-12 09:02
Hi! Thanks for bug reporting.

Please answer several questions:
1) Do you user ReactBridge inside your library?
2) What Xcode version do you use?
3) Can you provide a sample project to reproduce?

**Comment by Chaman-Sahu-iOS** [comment] 2024-01-12 16:36
1. Yes I am using ReactBridge inside my library.
2. I am Using Xcode 15.2.
3. Will share to you soon

**Comment by Chaman-Sahu-iOS** [comment] 2024-01-21 10:43
Hi, I found the root cause of the issue. 

There are two package dependencies - React Bridge & swift-syntax 
But they both have different iOS Deployment versions as attached with the given image-

<img width="751" alt="Screenshot 2024-01-21 at 4 08 07 PM" src="https://github.com/ikhvorost/ReactBridge/assets/118852284/48075cff-6fac-4c00-b57c-0a00f6f338f6">
<img width="551" alt="Screenshot 2024-01-21 at 4 08 17 PM" src="https://github.com/ikhvorost/ReactBridge/assets/118852284/341ec104-6fe0-424f-8f89-3b611cd5717b">

Please update this make with the same version it will solve the issue.

To reproduce the issue just create a xcFramework.

**Comment by Chaman-Sahu-iOS** [comment] 2024-01-22 07:02
I am adding a Sample Project also alongside this issue. 

To run the Framework command try this - 
-  Navigate to the project folder
-  Run this command:  **./ReactXcFramework.command**

The issue will reproduce when you add the React Bridge Dependency.

If you remove the React Bridge then it will work fine.

[ReactBridgeIssue.zip](https://github.com/ikhvorost/ReactBridge/files/14006281/ReactBridgeIssue.zip)

**Comment by ikhvorost** [comment] 2024-01-22 20:22
The issue is fixed in [1.0.3](https://github.com/ikhvorost/ReactBridge/releases/tag/1.0.3), please try it out.

**Closed** 2024-02-04 15:22 UTC
